language: node_js

node_js:
  - '12'

stages:
  - test
  - name: deploy
    if: branch = master
  - name: release
    if: branch = master

jobs:
  include:
    - stage: test           
      name: "Run tests"            # names the first Tests stage job
      script:
        - npm run test

    - stage: deploy
      name: "Build example"
      before_deploy:
        - cd example 
        - npm install 
        - npm run build
      name: "Deploy to surge.sh"
      deploy:
        provider: surge
        project: ./example/dist
        domain: use-cornify.surge.sh
        skip_cleanup: true

    - stage: release
      name: "Release to NPM"
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
