language: node_js
node_js:
  - '12'

jobs:
  include:
    - stage: test             
      name: "Run tests"            # names the first Tests stage job
      script:
        - npm run test
    - stage: before_deploy
      name: "Build example"
      script:
      - cd example 
      - npm install 
      - npm run build
    - stage: deploy
      name: "Deploy to surge.sh"
      deploy:
        provider: surge
        project: ./example/dist
        domain: use-cornify.surge.sh
        skip_cleanup: true
        on:
          branch: master
    - stage: release
      name: "Release to NPM"
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
